export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const REDIRECTED = 'REDIRECTED';

export const FETCH_SEARCH_EVENTS = 'FETCH_SEARCH_EVENTS';
export const FETCH_APPROVED_EVENTS = 'FETCH_APPROVED_EVENTS';
export const FETCH_USER_EVENTS = 'FETCH_USER_EVENTS';
export const FETCH_USER_TICKETS = 'FETCH_USER_TICKETS';

export const CREATE_EVENT = 'CREATE_EVENT';