export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const REDIRECTED = 'REDIRECTED';

export const FETCH_SEARCH_EVENTS = 'FETCH_SEARCH_EVENTS';
export const FETCH_APPROVED_EVENTS = 'FETCH_APPROVED_EVENTS';
export const FETCH_PENDING_EVENTS = 'FETCH_PENDING_EVENTS';
export const FETCH_EVENT_BY_ID = 'FETCH_EVENT_BY_ID';
export const FETCH_USER_EVENTS = 'FETCH_USER_EVENTS';
export const FETCH_USER_TICKETS = 'FETCH_USER_TICKETS';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_TICKET = 'CREATE_TICKET';
export const EDIT_EVENT = 'EDIT_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';

export const APPROVE_EVENT = 'APPROVE_EVENT';